# Generated by Django 4.2.13 on 2026-04-18 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'party_parties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System categories are seeded by the app and cannot be modified via the API.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Party Category',
                'verbose_name_plural': 'Party Categories',
                'db_table': 'party_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='party.party')),
            ],
            options={
                'verbose_name': 'Party Note',
                'verbose_name_plural': 'Party Notes',
                'db_table': 'party_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='parties/attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='party.party')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party Attachment',
                'verbose_name_plural': 'Party Attachments',
                'db_table': 'party_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('from_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_member', to='party.party')),
                ('to_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_org', to='party.party')),
            ],
            options={
                'verbose_name': 'Party Relationship',
                'verbose_name_plural': 'Party Relationships',
                'db_table': 'party_relationships',
                'ordering': ['-is_active', '-started_on', '-created_at'],
                'indexes': [models.Index(fields=['to_party', 'is_active'], name='party_rel_to_active_idx')],
                'unique_together': {('from_party', 'to_party', 'role')},
            },
        ),
        migrations.CreateModel(
            name='PartyCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_category_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='party.partycategory')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='party.party')),
            ],
            options={
                'verbose_name': 'Party Category Assignment',
                'verbose_name_plural': 'Party Category Assignments',
                'db_table': 'party_category_assignments',
                'ordering': ['category__name'],
                'unique_together': {('party', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('billing', 'Billing'), ('delivery', 'Delivery'), ('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='party.party')),
            ],
            options={
                'verbose_name': 'Party Address',
                'verbose_name_plural': 'Party Addresses',
                'db_table': 'party_addresses',
                'ordering': ['-is_default', 'label'],
                'indexes': [models.Index(fields=['party', 'is_default'], name='party_address_default_idx')],
            },
        ),
    ]
