# Generated by Django 4.2.13 on 2026-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_partyrelationship_to_party_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], db_index=True, max_length=20),
        ),
    ]
